### PR TITLE
also load api proxy in content scripts

### PR DESCRIPTION
**Pull request by minj**

### CODE REVIEW

**Comment by abarreir** [comment]
Nice catch!

One issue i see here is the possibility for the proxying to happen several time if there's such rule in the manifest:

``` json
{
    "content_scripts": [{
        "matches": ["http://*/*", "https://*/*", "file://*/*"],
        "js": ["foo.js"]
    }, {
        "matches": ["http://*/*", "https://*/*", "file://*/*"],
        "js": ["bar.js"]
    }]
}
```

What do you think about adding the following rule instead?

``` json
{
    "content_scripts": [{
        "matches": ["http://*/*", "https://*/*", "file://*/*"],
        "js": ["chrome-apis-proxy.js"],
        "run_at": "document_start"
    }, ... ]
}
```

This way we're sure the proxy is present on each page, and is loaded before any other content script.

**Comment by minj** [comment]
I assumed the only reason one would use different entries for js is if `matches` was different. But then again, nothing enforces XOR there. Now that I thought about it `run_at` is another reason....

Your solution is better but does that it work without `<all_urls>` permission?

**Comment by abarreir** [comment]
Well it could also happen if you inject a script on all pages, and have extra rule to inject another script on specific pages (speaking from experience here)

My solution would indeed not work without `<all_urls>`.

We could also modify the proxy code to add a custom property on the proxied chrome object, and not redefine it if the property is present. Not really elegant, but that would work with your proposed implementation.

**Comment by minj** [comment]
Seems my email got lost?

---

I don't know which is more inelegant, adding additional permissions
(don't forget you would need to check that `<all_urls>` is not there
already) or adding a flag on the proxy...

Well, considering optional permissions do not actually work at the
moment, `<all_urls>` might be somewhat beneficial.

Directly publishing the converted addon is not a reasonable use case,
is it? This tool is chiefly meant for testing, is it not?

**Comment by minj** [comment]
Speaking of the proxy. I think `chrome.*.lastError` should be excluded.

Here's the situation I ran into:

``` js
chrome.notifications.create(id, options, function(nId) {
    var err = chrome.runtime.lastError;
    if (err && /^Adding buttons/.test(err.message)) {
        // opera does not support buttons
        delete options.buttons;
        opts = options;
        retry();
    }
});
```

Due to proxy, `chrome.runtime.lastError` exists, and so does `chrome.runtime.lastError.message`. Alas it cannot be converted into a string ;)

**Comment by abarreir** [comment]
Only for testing purpose it is, although nothing would prevent devs from publishing a generated package. Maybe we should display a warning message when the conversion capability is used.

Ah, didn't think about lastError! Agreed it should be excluded.

**Comment by minj** [comment]
So... how do we resolve this?

P. S. I wanted to thank you for starting this project. I find it incredibly useful.
Oh and thanks for accepting my PRs. I can now practically run it directly on my extension's working dir ;)

**Comment by abarreir** [comment]
I think adding the `<all_urls>` permission (if not exists) is fine for now, any other solution might be hard to stabilise.

P.S. I'm happy this is useful to you, thanks for going the extra mile with your PRs!

**Comment by minj** [comment]
@abarreir I have rebased and rewritten the injection

Additionally I've improved proxy logging and added an option to disable the proxy altogether

**Comment by minj** [comment]
@abarreir I tried not to introduce any backwards-incompatibility with my commits. I can rewrite those if you don't feel that is a big deal

**Comment by abarreir** [comment]
@minj at this stage I don't feel this is a big deal, I didn't even document the api use yet.

**Comment by minj** [comment]
@abarreir anything else needed here?

**Comment by abarreir** [comment]
@minj sorry didn't see your latest commit :)

**Comment by minj** [comment]
thanks :+1:

**Pull request merged**
