### PR TITLE
skip .git directories

### PR DESCRIPTION
**Pull request by minj**
I think this makes sense when loading a directory.

The question of course is, do you support other VCS?

### CODE REVIEW

**Comment by abarreir** [comment]
What about simply filtering out all dot-folders instead?

**Comment by minj** [comment]
As far as I can tell, the fs.copy filter only gives you the path no other information. So you cannot distinguish a file from a folder. And skipping all dot files might be overkill

**Comment by minj** [comment]
Here is the relevant line: https://github.com/jprichardson/node-fs-extra/blob/master/lib/copy/ncp.js#L42

**Comment by abarreir** [comment]
Fair enough. I'll add support for mercurial and svn filtering!

**Comment by abarreir** [comment]
@minj Added mercurial and svn filtering: 0ebfb02

**Pull request merged**
