### PR TITLE
try to recover when manifest parsing fails due to comments in JSON

### PR DESCRIPTION
**Pull request by minj**
it is possible to use comments in manifest.json in chrome
at least in dev mode

however Mozilla devs decided to WONTFIX it:
https://bugzilla.mozilla.org/show_bug.cgi?id=1196283

### CODE REVIEW

**Comment by minj** [comment]
Speaking of the manifest. I think it would be worthwhile to pretty-print it, i. e. `JSON.stringify(m, null, '\t');`

**Comment by abarreir** [comment]
+1 for pretty printing, will add it. Shouldn't we return originalError in the callback instead of throwing it?

**Comment by minj** [comment]
I know it's supposed to be standard and all but after testing it on node throwing seems to give better context information. Although I can change it if you prefer

**Comment by abarreir** [comment]
It does not really matter when used as a cli, I think it would be better when used by another module though.

**Pull request merged**
